name: Check Code

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint
        run: yarn lint
      
      - name: Check formatting
        run: yarn format:check

      - name: Run typecheck
        run: yarn typecheck

